import pandas as pd
import matplotlib.pyplot as plt
import xgboost as xgb
from sklearn.metrics import accuracy_score

import quandl
quandl.ApiConfig.api_key = "5UDsQj-5EYJNHoo8UbKu"

df = quandl.get("WIKI/AMZN")

#Load the data from a csv file.
CNHI = {"stock_name":"AMAZON", "data": df}
CNHI["data"]=CNHI["data"].drop(df.columns[[5,6,7,8,9,10,11]], axis=1)
# print(CNHI['data'])

Predictors = pd.DataFrame({"sma2":CNHI["data"].Open.rolling(window=2).mean()})
Predictors["sma2_1"] = Predictors.sma2.shift(1)

Predictors["sma2_increment"] = Predictors.sma2.diff()  

Predictors["sma2_1_increment"] = Predictors.sma2_1.diff()  

Predictors["vol_increment"] = CNHI["data"].Volume.diff()

Predictors["vol_rel_increment"] = CNHI["data"].Volume.diff() / CNHI["data"].Volume

Predictors["open_1"] = CNHI["data"].Open.shift(1)

Predictors["open_incr"] = CNHI["data"].Open - CNHI["data"].Open.shift(1)

Predictors["open"] = CNHI["data"].Open

# The rows with nulls generated by rolling values will be removed.
Predictors = Predictors.dropna()